# Generated by Django 2.1.7 on 2019-06-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_auto_20190315_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='department',
            field=models.CharField(blank=True, choices=[('BAS', 'Basees Sendan,'), ('BT', 'Boting Department')], max_length=255, null=True, verbose_name='dept of Lead'),
        ),
    ]
