# Generated by Django 2.1.7 on 2019-06-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_lead_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='pre_bid_status',
            field=models.CharField(blank=True, choices=[('B', 'Budgetary'), ('L', 'Live')], max_length=255, null=True, verbose_name='pre_bid_status'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='department',
            field=models.CharField(blank=True, choices=[('BAS', 'Basees Sendan,'), ('BT', 'Boting Department'), ('CIVIL', 'Civil construction'), ('CSD', 'Construction Services Department'), ('E & I', 'Electrical & Instrumentation Construction'), ('ETD', 'Equipment & Transport Department'), ('HRS', 'Human Resource Services'), ('HSE', 'Health, Safety & Envirnomnent (Pro Safe)'), ('Mech', 'Mechanical Construction'), ('PSD', 'Plant Servicse Department'), ('RGSS', 'Redguard Specialist Services'), ('SCF', 'Scaffolding Services'), ('SP', 'Site Projects'), ('TNC', 'Electrical Maintenance, Testing & Commissioning Services (SHOUAA)'), ('TSD', 'Technical Services Division')], max_length=255, null=True, verbose_name='dept of Lead'),
        ),
    ]
