# Generated by Django 2.1.7 on 2019-06-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_auto_20190614_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='region',
            field=models.CharField(blank=True, choices=[('C', 'Central'), ('E', 'East'), ('W', 'West')], max_length=255, null=True, verbose_name='region'),
        ),
    ]
