# Generated by Django 2.1.7 on 2019-06-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_lead_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, choices=[('assigned', 'Assigned'), ('in process', 'In Process'), ('converted', 'Converted'), ('recycled', 'Recycled'), ('closed', 'Closed'), ('A', 'Award (Last year bided job awarded in current year)'), ('Ad', 'Awarded (Current year Bided job awarded)'), ('D', 'Decline'), ('H', 'Hold by Client'), ('LC', 'Lost Commercialy'), ('LT', 'Lost Technicaly'), ('S', 'Submitted'), ('UP', 'Under Preparation')], max_length=255, null=True, verbose_name='Status of Lead'),
        ),
    ]
