# Generated by Django 2.1.7 on 2019-06-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_auto_20190619_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='department',
        ),
        migrations.AddField(
            model_name='lead',
            name='department',
            field=models.ManyToManyField(related_name='department', to='leads.Department'),
        ),
    ]
