# Generated by Django 2.1.7 on 2019-06-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_auto_20190619_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='lead_contacts', to='contacts.Contact'),
        ),
    ]
